"""init

Revision ID: 95eaa957d510
Revises: None
Create Date: 2016-11-05 15:17:45.910624

"""

# revision identifiers, used by Alembic.
revision = '95eaa957d510'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    ### end Alembic commands ###
